/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.sem1.hms.other;

import edu.ijse.sem1.hms.view.HomePage;

/**
 *
 * @author Achini & Samadhi
 */
public class Gallery2 extends javax.swing.JFrame {

    /**
     * Creates new form Gallery2
     */
    public Gallery2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        galleryLabel = new javax.swing.JLabel();
        poolLabel = new javax.swing.JLabel();
        poolImage = new javax.swing.JLabel();
        hallImage = new javax.swing.JLabel();
        hallLabel = new javax.swing.JLabel();
        previousPageIcon = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        backgroundIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(null);

        galleryLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        galleryLabel.setForeground(new java.awt.Color(255, 255, 255));
        galleryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        galleryLabel.setText("Gallery");
        mainPanel.add(galleryLabel);
        galleryLabel.setBounds(600, 10, 160, 40);

        poolLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        poolLabel.setForeground(new java.awt.Color(255, 255, 255));
        poolLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poolLabel.setText("Swimming Pool");
        mainPanel.add(poolLabel);
        poolLabel.setBounds(60, 70, 140, 30);

        poolImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        poolImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/DSC_8046-.jpg"))); // NOI18N
        mainPanel.add(poolImage);
        poolImage.setBounds(10, 100, 980, 630);

        hallImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hallImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/001.jpg"))); // NOI18N
        mainPanel.add(hallImage);
        hallImage.setBounds(990, 100, 400, 480);

        hallLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hallLabel.setForeground(new java.awt.Color(255, 255, 255));
        hallLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hallLabel.setText("Large Halls");
        mainPanel.add(hallLabel);
        hallLabel.setBounds(994, 570, 400, 30);

        previousPageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previousPageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f060(0)_85.png"))); // NOI18N
        previousPageIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousPageIconMouseClicked(evt);
            }
        });
        mainPanel.add(previousPageIcon);
        previousPageIcon.setBounds(1260, 650, 85, 80);

        homeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f015(0)_85.png"))); // NOI18N
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
        });
        mainPanel.add(homeIcon);
        homeIcon.setBounds(1170, 650, 80, 80);

        backgroundIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/2016-05-01-20-13-48-481.jpg"))); // NOI18N
        mainPanel.add(backgroundIcon);
        backgroundIcon.setBounds(-6, -6, 1440, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1434, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        new HomePage().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeIconMouseClicked

    private void previousPageIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousPageIconMouseClicked
        new Gallery1().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_previousPageIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gallery2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gallery2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gallery2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gallery2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gallery2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundIcon;
    private javax.swing.JLabel galleryLabel;
    private javax.swing.JLabel hallImage;
    private javax.swing.JLabel hallLabel;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel poolImage;
    private javax.swing.JLabel poolLabel;
    private javax.swing.JLabel previousPageIcon;
    // End of variables declaration//GEN-END:variables
}
