/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.sem1.hms.view;

import edu.ijse.sem1.hms.view.*;
/**
 *
 * @author Achini & Samadhi
 */
public class ContactDetails extends javax.swing.JFrame {

    /**
     * Creates new form ContcactDetails
     */
    public ContactDetails() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        contactDetails = new javax.swing.JLabel();
        dotLine = new javax.swing.JLabel();
        hotelAddress = new javax.swing.JLabel();
        telNum1 = new javax.swing.JLabel();
        telNum2 = new javax.swing.JLabel();
        telNum3 = new javax.swing.JLabel();
        homeIcon = new javax.swing.JLabel();
        backgroundIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        contactDetails.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        contactDetails.setForeground(new java.awt.Color(255, 255, 255));
        contactDetails.setText("Contact Details");
        jPanel1.add(contactDetails);
        contactDetails.setBounds(180, 10, 200, 29);

        dotLine.setForeground(new java.awt.Color(255, 255, 255));
        dotLine.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dotLine.setText(".................................................................");
        jPanel1.add(dotLine);
        dotLine.setBounds(130, 50, 260, 14);

        hotelAddress.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hotelAddress.setForeground(new java.awt.Color(255, 255, 255));
        hotelAddress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelAddress.setText("Ramadan Hotel, 264, Old Galle Road, Gorakana, Moratuwa");
        jPanel1.add(hotelAddress);
        hotelAddress.setBounds(100, 70, 390, 30);

        telNum1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telNum1.setForeground(new java.awt.Color(255, 255, 255));
        telNum1.setText("Tel  :038 2298645        Fax        :011 2713689");
        jPanel1.add(telNum1);
        telNum1.setBounds(110, 110, 310, 20);

        telNum2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telNum2.setForeground(new java.awt.Color(255, 255, 255));
        telNum2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        telNum2.setText("  038 3385855        Hot Line :071 2401936");
        jPanel1.add(telNum2);
        telNum2.setBounds(110, 140, 310, 20);

        telNum3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telNum3.setForeground(new java.awt.Color(255, 255, 255));
        telNum3.setText("011 4380096");
        jPanel1.add(telNum3);
        telNum3.setBounds(140, 170, 90, 20);

        homeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f015(0)_85.png"))); // NOI18N
        homeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeIconMouseClicked(evt);
            }
        });
        jPanel1.add(homeIcon);
        homeIcon.setBounds(440, 260, 80, 80);

        backgroundIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/2016-05-01-20-13-48-481.jpg"))); // NOI18N
        jPanel1.add(backgroundIcon);
        backgroundIcon.setBounds(-6, -6, 540, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeIconMouseClicked
        new HomePage().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundIcon;
    private javax.swing.JLabel contactDetails;
    private javax.swing.JLabel dotLine;
    private javax.swing.JLabel homeIcon;
    private javax.swing.JLabel hotelAddress;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel telNum1;
    private javax.swing.JLabel telNum2;
    private javax.swing.JLabel telNum3;
    // End of variables declaration//GEN-END:variables
}
