/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.sem1.hms.view;



import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

import javax.swing.JOptionPane;

/**
 *
 * @author Achini & Samadhi
 */
public class CreateUserAccount extends javax.swing.JFrame {

    /**
     * Creates new form CreateUserAccount
     */
    public CreateUserAccount() {
        initComponents();
        
    }

     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createUserAccount = new javax.swing.JLabel();
        employeeID = new javax.swing.JLabel();
        empIDText = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        userNameText = new javax.swing.JTextField();
        cancelLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        password1 = new javax.swing.JLabel();
        pwd = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        passwordText1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        createUserAccount.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        createUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        createUserAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createUserAccount.setText("Create User Account");
        jPanel1.add(createUserAccount);
        createUserAccount.setBounds(80, 10, 390, 44);

        employeeID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        employeeID.setForeground(new java.awt.Color(255, 255, 255));
        employeeID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeeID.setText("Employee ID");
        jPanel1.add(employeeID);
        employeeID.setBounds(30, 90, 101, 30);

        empIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empIDTextActionPerformed(evt);
            }
        });
        jPanel1.add(empIDText);
        empIDText.setBounds(200, 90, 70, 30);

        userName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        userName.setText("User Name");
        jPanel1.add(userName);
        userName.setBounds(30, 210, 90, 30);

        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(userNameText);
        userNameText.setBounds(200, 210, 330, 30);

        cancelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f015(0)_85.png"))); // NOI18N
        cancelLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelLabelMouseClicked(evt);
            }
        });
        jPanel1.add(cancelLabel);
        cancelLabel.setBounds(290, 310, 85, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("First Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 130, 90, 30);

        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameText);
        firstNameText.setBounds(200, 130, 300, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Last Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 170, 83, 30);

        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameText);
        lastNameText.setBounds(200, 170, 300, 30);

        password1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        password1.setForeground(new java.awt.Color(255, 255, 255));
        password1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        password1.setText("Password");
        jPanel1.add(password1);
        password1.setBounds(30, 250, 80, 30);
        jPanel1.add(pwd);
        pwd.setBounds(200, 250, 330, 30);

        jButton1.setText("Add User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(440, 320, 90, 40);

        passwordText1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordText1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/2016-05-01-20-13-48-481.jpg"))); // NOI18N
        jPanel1.add(passwordText1);
        passwordText1.setBounds(0, 0, 580, 450);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 370, 73, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextActionPerformed

    private void cancelLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelLabelMouseClicked
        new HomePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelLabelMouseClicked
    
    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        //xsxs TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String empid=empIDText.getText();
        String fname=firstNameText.getText();
        String lname=lastNameText.getText();
        String username=userNameText.getText();
        String ch=String.valueOf(pwd.getPassword());     
        
        

       

        

            authen(empid,fname,lname,username,ch);

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void empIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empIDTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelLabel;
    private javax.swing.JLabel createUserAccount;
    private javax.swing.JTextField empIDText;
    private javax.swing.JLabel employeeID;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel password1;
    private javax.swing.JLabel passwordText1;
    private javax.swing.JPasswordField pwd;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField userNameText;
    // End of variables declaration//GEN-END:variables

    private void authen(String empid, String fname, String lname, String username, String ch) {
        try{
            Connection conn = connect();
            String sql = "INSERT INTO `users` SET `empid`='"+empid+"',`fname`='"+fname+"',`lname`='"+lname+"',`username`='"+username+"',`password`='"+ch+"'";
                    int success = conn.createStatement().executeUpdate(sql);
            if (success == 1){
                System.out.println("success");
            }else{
                System.out.println("error");
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }

    private Connection connect() throws ClassNotFoundException, SQLException {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/useradd","root","");
        return conn;
    }
}
