/*



 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.sem1.hms.view;

import edu.ijse.sem1.hms.other.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 *
 * @author Achini & Samadhi
 */
public class HomePage extends javax.swing.JFrame {
    public static boolean d=true;
    public static boolean b=true;
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        setLocationRelativeTo(null);
        setDateTime();
        createUserButton.setEnabled(d);
        informationButton.setEnabled(b);
    }
    private void setDateTime() {
        dateLabel.setText(new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime()));
        Thread time = new Thread() {

            public void run() {
                while (true) {
                    Date date = new Date();
                    SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm:ss a");
                    String formatedTime = dateFormat.format(date);
                    timeLabel.setText(formatedTime);
                }

            }
        };
        time.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainHomePanel = new javax.swing.JPanel();
        hotelNameLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        logoutIcon = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        checkInPanel = new javax.swing.JPanel();
        checkInIcon = new javax.swing.JLabel();
        checkInButton = new javax.swing.JButton();
        mealPanel = new javax.swing.JPanel();
        mealButton = new javax.swing.JButton();
        mealIcon = new javax.swing.JLabel();
        reservationPanel = new javax.swing.JPanel();
        reservationIcon = new javax.swing.JLabel();
        reservationButton = new javax.swing.JButton();
        createUserPanel = new javax.swing.JPanel();
        createUserIcon = new javax.swing.JLabel();
        createUserButton = new javax.swing.JButton();
        galleryPanel = new javax.swing.JPanel();
        galleryIcon = new javax.swing.JLabel();
        galleryButton = new javax.swing.JButton();
        informationPanel = new javax.swing.JPanel();
        informationIcon = new javax.swing.JLabel();
        informationButton = new javax.swing.JButton();
        panelLabel = new javax.swing.JLabel();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainHomePanel.setLayout(null);

        hotelNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hotelNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/logo.png"))); // NOI18N
        mainHomePanel.add(hotelNameLabel);
        hotelNameLabel.setBounds(0, 0, 180, 90);

        timeLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        timeLabel.setForeground(new java.awt.Color(255, 255, 255));
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHomePanel.add(timeLabel);
        timeLabel.setBounds(10, 90, 160, 40);

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dateLabel.setForeground(new java.awt.Color(255, 255, 255));
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainHomePanel.add(dateLabel);
        dateLabel.setBounds(10, 130, 150, 30);

        logoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f011(0)_32.png"))); // NOI18N
        mainHomePanel.add(logoutIcon);
        logoutIcon.setBounds(900, 10, 40, 40);

        logoutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logoutButton.setText("Log Out");
        logoutButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        mainHomePanel.add(logoutButton);
        logoutButton.setBounds(900, 10, 110, 40);

        buttonPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonPanel.setLayout(null);

        checkInPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        checkInPanel.setOpaque(false);
        checkInPanel.setLayout(null);

        checkInIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        checkInIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f0b1(0)_64.png"))); // NOI18N
        checkInPanel.add(checkInIcon);
        checkInIcon.setBounds(10, 10, 120, 70);

        checkInButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkInButton.setText("Payment");
        checkInButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        checkInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInButtonActionPerformed(evt);
            }
        });
        checkInPanel.add(checkInButton);
        checkInButton.setBounds(10, 90, 120, 40);

        buttonPanel.add(checkInPanel);
        checkInPanel.setBounds(340, 10, 140, 140);

        mealPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mealPanel.setOpaque(false);
        mealPanel.setLayout(null);

        mealButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mealButton.setText("Meal");
        mealButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        mealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mealButtonActionPerformed(evt);
            }
        });
        mealPanel.add(mealButton);
        mealButton.setBounds(10, 90, 120, 40);

        mealIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mealIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/linecons_e026(0)_128.png"))); // NOI18N
        mealPanel.add(mealIcon);
        mealIcon.setBounds(10, 0, 120, 80);

        buttonPanel.add(mealPanel);
        mealPanel.setBounds(170, 10, 140, 140);

        reservationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        reservationPanel.setOpaque(false);
        reservationPanel.setLayout(null);

        reservationIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/Material Icons_e7f7(0)_128_1.png"))); // NOI18N
        reservationPanel.add(reservationIcon);
        reservationIcon.setBounds(10, 10, 140, 90);

        reservationButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reservationButton.setText("Reservation");
        reservationButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        reservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservationButtonActionPerformed(evt);
            }
        });
        reservationPanel.add(reservationButton);
        reservationButton.setBounds(10, 90, 120, 40);

        buttonPanel.add(reservationPanel);
        reservationPanel.setBounds(10, 10, 140, 140);

        createUserPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        createUserPanel.setOpaque(false);
        createUserPanel.setLayout(null);

        createUserIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/Entypo_e700(0)_128.png"))); // NOI18N
        createUserPanel.add(createUserIcon);
        createUserIcon.setBounds(10, 10, 110, 80);

        createUserButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        createUserButton.setText("Create User");
        createUserButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        createUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createUserButtonActionPerformed(evt);
            }
        });
        createUserPanel.add(createUserButton);
        createUserButton.setBounds(10, 90, 120, 40);

        buttonPanel.add(createUserPanel);
        createUserPanel.setBounds(10, 160, 140, 140);

        galleryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        galleryPanel.setOpaque(false);
        galleryPanel.setLayout(null);

        galleryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        galleryIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/Entypo_d83c(0)_128.png"))); // NOI18N
        galleryPanel.add(galleryIcon);
        galleryIcon.setBounds(0, 0, 120, 80);

        galleryButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        galleryButton.setText("Gallery");
        galleryButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        galleryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                galleryButtonActionPerformed(evt);
            }
        });
        galleryPanel.add(galleryButton);
        galleryButton.setBounds(10, 90, 120, 40);

        buttonPanel.add(galleryPanel);
        galleryPanel.setBounds(170, 160, 140, 140);

        informationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        informationPanel.setOpaque(false);
        informationPanel.setLayout(null);

        informationIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informationIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f05a(0)_128.png"))); // NOI18N
        informationPanel.add(informationIcon);
        informationIcon.setBounds(0, 10, 128, 80);

        informationButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        informationButton.setText("Information");
        informationButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        informationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationButtonActionPerformed(evt);
            }
        });
        informationPanel.add(informationButton);
        informationButton.setBounds(10, 90, 120, 40);

        buttonPanel.add(informationPanel);
        informationPanel.setBounds(340, 160, 140, 140);

        panelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/ojayee.jpg"))); // NOI18N
        buttonPanel.add(panelLabel);
        panelLabel.setBounds(0, 0, 540, 300);

        mainHomePanel.add(buttonPanel);
        buttonPanel.setBounds(130, 300, 540, 290);

        mainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/2812651380_be93afdd80_b.jpg"))); // NOI18N
        mainHomePanel.add(mainLabel);
        mainLabel.setBounds(0, 10, 1024, 650);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        new UserLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void reservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservationButtonActionPerformed
        new Customer().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_reservationButtonActionPerformed

    private void mealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mealButtonActionPerformed
        new Meal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mealButtonActionPerformed

    private void galleryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_galleryButtonActionPerformed
        new Gallery().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_galleryButtonActionPerformed

    private void informationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationButtonActionPerformed
        new Information().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_informationButtonActionPerformed

    private void checkInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInButtonActionPerformed
        new Payment().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkInButtonActionPerformed

    private void createUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createUserButtonActionPerformed
        new CreateUserAccount().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton checkInButton;
    private javax.swing.JLabel checkInIcon;
    private javax.swing.JPanel checkInPanel;
    public static javax.swing.JButton createUserButton;
    private javax.swing.JLabel createUserIcon;
    private javax.swing.JPanel createUserPanel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton galleryButton;
    private javax.swing.JLabel galleryIcon;
    private javax.swing.JPanel galleryPanel;
    private javax.swing.JLabel hotelNameLabel;
    public static javax.swing.JButton informationButton;
    private javax.swing.JLabel informationIcon;
    private javax.swing.JPanel informationPanel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel logoutIcon;
    private javax.swing.JPanel mainHomePanel;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton mealButton;
    private javax.swing.JLabel mealIcon;
    private javax.swing.JPanel mealPanel;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JButton reservationButton;
    private javax.swing.JLabel reservationIcon;
    private javax.swing.JPanel reservationPanel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
