/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.sem1.hms.view;

import edu.ijse.sem1.hms.view.HomePage;


/**
 *
 * @author Achini & Samadhi
 */
public class RoomInformation extends javax.swing.JFrame {

    /**
     * Creates new form RoomInformation
     */
    public RoomInformation() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        roomInfoLabel = new javax.swing.JLabel();
        singleRoomImage = new javax.swing.JLabel();
        doubleRoomImage = new javax.swing.JLabel();
        familySuiteImage = new javax.swing.JLabel();
        singleRoomPrice = new javax.swing.JLabel();
        doubleRoomPrice = new javax.swing.JLabel();
        familySuitePrice = new javax.swing.JLabel();
        homepageIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backgroundIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(null);

        roomInfoLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        roomInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        roomInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomInfoLabel.setText("Room Information");
        mainPanel.add(roomInfoLabel);
        roomInfoLabel.setBounds(530, 10, 334, 50);

        singleRoomImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singleRoomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/SingleRoom.PNG"))); // NOI18N
        mainPanel.add(singleRoomImage);
        singleRoomImage.setBounds(30, 120, 410, 390);

        doubleRoomImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doubleRoomImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/DoubleRoom.PNG"))); // NOI18N
        mainPanel.add(doubleRoomImage);
        doubleRoomImage.setBounds(470, 110, 410, 410);

        familySuiteImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        familySuiteImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FamilySuite.PNG"))); // NOI18N
        mainPanel.add(familySuiteImage);
        familySuiteImage.setBounds(900, 110, 430, 410);

        singleRoomPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        singleRoomPrice.setForeground(new java.awt.Color(255, 255, 255));
        singleRoomPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        singleRoomPrice.setText("Price : LKR 1000");
        mainPanel.add(singleRoomPrice);
        singleRoomPrice.setBounds(36, 514, 400, 40);

        doubleRoomPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doubleRoomPrice.setForeground(new java.awt.Color(255, 255, 255));
        doubleRoomPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doubleRoomPrice.setText("Price : LKR 2000");
        mainPanel.add(doubleRoomPrice);
        doubleRoomPrice.setBounds(478, 514, 400, 40);

        familySuitePrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        familySuitePrice.setForeground(new java.awt.Color(255, 255, 255));
        familySuitePrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        familySuitePrice.setText("Price : LKR 5000");
        mainPanel.add(familySuitePrice);
        familySuitePrice.setBounds(918, 514, 400, 40);

        homepageIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homepageIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f015(0)_85.png"))); // NOI18N
        homepageIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homepageIconMouseClicked(evt);
            }
        });
        mainPanel.add(homepageIcon);
        homepageIcon.setBounds(1190, 680, 80, 80);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RT001");
        mainPanel.add(jLabel1);
        jLabel1.setBounds(200, 90, 57, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("RT002");
        mainPanel.add(jLabel2);
        jLabel2.setBounds(640, 92, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RT003");
        mainPanel.add(jLabel3);
        jLabel3.setBounds(1070, 92, 90, 30);

        backgroundIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/2016-05-01-20-13-48-481.jpg"))); // NOI18N
        mainPanel.add(backgroundIcon);
        backgroundIcon.setBounds(-6, -6, 1440, 900);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1432, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homepageIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepageIconMouseClicked
        new HomePage().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homepageIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundIcon;
    private javax.swing.JLabel doubleRoomImage;
    private javax.swing.JLabel doubleRoomPrice;
    private javax.swing.JLabel familySuiteImage;
    private javax.swing.JLabel familySuitePrice;
    private javax.swing.JLabel homepageIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel roomInfoLabel;
    private javax.swing.JLabel singleRoomImage;
    private javax.swing.JLabel singleRoomPrice;
    // End of variables declaration//GEN-END:variables
}
