/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.sem1.hms.view;

import edu.ijse.sem1.hms.controller.UserController;
import edu.ijse.sem1.hms.model.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Arrays;
import edu.ijse.sem1.hms.view.*;
import java.sql.ResultSet;
/**
 *
 * @author Achini & Samadhi
 */
public class UserLogin extends javax.swing.JFrame {
   
    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
.     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainIconLabel = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        stripePanel = new javax.swing.JPanel();
        userIconLabel = new javax.swing.JLabel();
        userTitleLabel = new javax.swing.JLabel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        userNameText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();

        mainIconLabel.setBackground(new java.awt.Color(255, 255, 255));
        mainIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/pizap.com14571501153221.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setLayout(null);

        stripePanel.setBackground(new java.awt.Color(255, 255, 255));
        stripePanel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout stripePanelLayout = new javax.swing.GroupLayout(stripePanel);
        stripePanel.setLayout(stripePanelLayout);
        stripePanelLayout.setHorizontalGroup(
            stripePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        stripePanelLayout.setVerticalGroup(
            stripePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        mainPanel.add(stripePanel);
        stripePanel.setBounds(0, 160, 570, 10);

        userIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/sem1/hms/images/FontAwesome_f007(0)_128.png"))); // NOI18N
        mainPanel.add(userIconLabel);
        userIconLabel.setBounds(70, 10, 120, 130);

        userTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        userTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userTitleLabel.setText("USER LOGIN");
        mainPanel.add(userTitleLabel);
        userTitleLabel.setBounds(200, 40, 270, 58);

        userNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        userNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameLabel.setText("User Name");
        mainPanel.add(userNameLabel);
        userNameLabel.setBounds(40, 190, 160, 29);

        passwordLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        passwordLabel.setText("Password");
        mainPanel.add(passwordLabel);
        passwordLabel.setBounds(50, 290, 130, 29);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("LOGIN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1);
        jButton1.setBounds(190, 450, 150, 31);

        userNameText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        userNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextActionPerformed(evt);
            }
        });
        mainPanel.add(userNameText);
        userNameText.setBounds(80, 230, 420, 40);
        mainPanel.add(passwordText);
        passwordText.setBounds(80, 350, 410, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String user = userNameText.getText();
        String password = passwordText.getText();
        try {
              boolean login = UserController.login(user,password);
//            String user=userNameText.getText();
            if (login == true) {
                if(passwordText.getText().equals("Admin")){
                new HomePage().setVisible(true);
                this.dispose();
               
               }
                else{
                    HomePage.d=false;
                    HomePage.b=false;
                    new HomePage().setVisible(true);
                    dispose();
                }
                
            } else if(login == false) {
                JOptionPane.showMessageDialog(this,"UserName or Password Incorrect");
            }
            else  {
                JOptionPane.showMessageDialog(this,"UserName or Password Incorrect");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(UserLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    // TODO add your handling code here:
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextActionPerformed

                                           
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mainIconLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JPanel stripePanel;
    private javax.swing.JLabel userIconLabel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameText;
    private javax.swing.JLabel userTitleLabel;
    // End of variables declaration//GEN-END:variables
}
